export module crumb.render:rhi_types;

// ============================================================================
// RHI Types — 渲染硬件抽象层 枚举/类型定义
// 所有枚举值精确匹配 Vulkan C 枚举值，可直接 static_cast
// 本模块不依赖任何 Vulkan 头文件
// ============================================================================

import std;

export namespace Crumb::Render {

// ============================================================================
// 常量
// ============================================================================
inline constexpr auto RHI_NULL_HANDLE                    = nullptr;
inline constexpr std::uint64_t RHI_WHOLE_SIZE            = ~0ULL;
inline constexpr std::uint32_t RHI_SUBPASS_EXTERNAL      = ~0U;
inline constexpr std::uint32_t RHI_QUEUE_FAMILY_IGNORED  = ~0U;
inline constexpr int RHI_MAX_EXTENSION_NAME_SIZE         = 256;
inline constexpr int RHI_MAX_DESCRIPTION_SIZE            = 256;
inline constexpr int RHI_MAX_PHYSICAL_DEVICE_NAME_SIZE   = 256;
inline constexpr int RHI_UUID_SIZE                       = 16;
inline constexpr int RHI_MAX_MEMORY_TYPES                = 32;
inline constexpr int RHI_MAX_MEMORY_HEAPS                = 16;

// ============================================================================
// 基础类型别名
// ============================================================================
using RHIDeviceSize = std::uint64_t;
using RHIBool32 = std::uint32_t;
using RHIDeviceAddress = std::uint64_t;

// 前向声明的 Flags 类型（在对应枚举定义后补充）
using RHIRenderingInfoFlags = std::uint32_t;

// ============================================================================
// RHIStructureType — 结构体类型标识
// ============================================================================
enum RHIStructureType : int {
    RHI_STRUCTURE_TYPE_APPLICATION_INFO = 0,
    RHI_STRUCTURE_TYPE_INSTANCE_CREATE_INFO = 1,
    RHI_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO = 2,
    RHI_STRUCTURE_TYPE_DEVICE_CREATE_INFO = 3,
    RHI_STRUCTURE_TYPE_SUBMIT_INFO = 4,
    RHI_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO = 5,
    RHI_STRUCTURE_TYPE_FENCE_CREATE_INFO = 8,
    RHI_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO = 9,
    RHI_STRUCTURE_TYPE_BUFFER_CREATE_INFO = 12,
    RHI_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO = 13,
    RHI_STRUCTURE_TYPE_IMAGE_CREATE_INFO = 14,
    RHI_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO = 15,
    RHI_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO = 16,
    RHI_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO = 18,
    RHI_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO = 19,
    RHI_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO = 20,
    RHI_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO = 22,
    RHI_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO = 23,
    RHI_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO = 24,
    RHI_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO = 25,
    RHI_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO = 26,
    RHI_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO = 27,
    RHI_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO = 28,
    RHI_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO = 29,
    RHI_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO = 30,
    RHI_STRUCTURE_TYPE_SAMPLER_CREATE_INFO = 31,
    RHI_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO = 32,
    RHI_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO = 33,
    RHI_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO = 34,
    RHI_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET = 35,
    RHI_STRUCTURE_TYPE_COPY_DESCRIPTOR_SET = 36,
    RHI_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO = 37,
    RHI_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO = 38,
    RHI_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO = 39,
    RHI_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO = 40,
    RHI_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO = 42,
    RHI_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO = 43,
    RHI_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER = 44,
    RHI_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER = 45,
    RHI_STRUCTURE_TYPE_MEMORY_BARRIER = 46,
    RHI_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2 = 1000059000,
    RHI_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2 = 1000059001,
    RHI_STRUCTURE_TYPE_FORMAT_PROPERTIES_2 = 1000059002,
    RHI_STRUCTURE_TYPE_IMAGE_FORMAT_PROPERTIES_2 = 1000059003,
    RHI_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR = 1000001000,
    RHI_STRUCTURE_TYPE_PRESENT_INFO_KHR = 1000001001,
    RHI_STRUCTURE_TYPE_RENDERING_INFO_KHR = 1000044000,
    RHI_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO_KHR = 1000044001,
    RHI_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO_KHR = 1000044002,
    RHI_STRUCTURE_TYPE_PHYSICAL_DEVICE_DYNAMIC_RENDERING_FEATURES_KHR = 1000044003,
    RHI_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_FEATURES = 49,
    RHI_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_FEATURES = 51,
    RHI_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_FEATURES = 57,
    RHI_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_4_FEATURES = 69,
    RHI_STRUCTURE_TYPE_MAX_ENUM = 0x7FFFFFFF
};

// ============================================================================
// RHIFormat — 像素格式（值匹配 VkFormat）
// ============================================================================
enum RHIFormat : int {
    RHI_FORMAT_UNDEFINED = 0,
    RHI_FORMAT_R4G4_UNORM_PACK8 = 1,
    RHI_FORMAT_R4G4B4A4_UNORM_PACK16 = 2,
    RHI_FORMAT_B4G4R4A4_UNORM_PACK16 = 3,
    RHI_FORMAT_R5G6B5_UNORM_PACK16 = 4,
    RHI_FORMAT_B5G6R5_UNORM_PACK16 = 5,
    RHI_FORMAT_R5G5B5A1_UNORM_PACK16 = 6,
    RHI_FORMAT_B5G5R5A1_UNORM_PACK16 = 7,
    RHI_FORMAT_A1R5G5B5_UNORM_PACK16 = 8,
    RHI_FORMAT_R8_UNORM = 9,
    RHI_FORMAT_R8_SNORM = 10,
    RHI_FORMAT_R8_USCALED = 11,
    RHI_FORMAT_R8_SSCALED = 12,
    RHI_FORMAT_R8_UINT = 13,
    RHI_FORMAT_R8_SINT = 14,
    RHI_FORMAT_R8_SRGB = 15,
    RHI_FORMAT_R8G8_UNORM = 16,
    RHI_FORMAT_R8G8_SNORM = 17,
    RHI_FORMAT_R8G8_USCALED = 18,
    RHI_FORMAT_R8G8_SSCALED = 19,
    RHI_FORMAT_R8G8_UINT = 20,
    RHI_FORMAT_R8G8_SINT = 21,
    RHI_FORMAT_R8G8_SRGB = 22,
    RHI_FORMAT_R8G8B8_UNORM = 23,
    RHI_FORMAT_R8G8B8_SNORM = 24,
    RHI_FORMAT_R8G8B8_USCALED = 25,
    RHI_FORMAT_R8G8B8_SSCALED = 26,
    RHI_FORMAT_R8G8B8_UINT = 27,
    RHI_FORMAT_R8G8B8_SINT = 28,
    RHI_FORMAT_R8G8B8_SRGB = 29,
    RHI_FORMAT_B8G8R8_UNORM = 30,
    RHI_FORMAT_B8G8R8_SNORM = 31,
    RHI_FORMAT_B8G8R8_USCALED = 32,
    RHI_FORMAT_B8G8R8_SSCALED = 33,
    RHI_FORMAT_B8G8R8_UINT = 34,
    RHI_FORMAT_B8G8R8_SINT = 35,
    RHI_FORMAT_B8G8R8_SRGB = 36,
    RHI_FORMAT_R8G8B8A8_UNORM = 37,
    RHI_FORMAT_R8G8B8A8_SNORM = 38,
    RHI_FORMAT_R8G8B8A8_USCALED = 39,
    RHI_FORMAT_R8G8B8A8_SSCALED = 40,
    RHI_FORMAT_R8G8B8A8_UINT = 41,
    RHI_FORMAT_R8G8B8A8_SINT = 42,
    RHI_FORMAT_R8G8B8A8_SRGB = 43,
    RHI_FORMAT_B8G8R8A8_UNORM = 44,
    RHI_FORMAT_B8G8R8A8_SNORM = 45,
    RHI_FORMAT_B8G8R8A8_USCALED = 46,
    RHI_FORMAT_B8G8R8A8_SSCALED = 47,
    RHI_FORMAT_B8G8R8A8_UINT = 48,
    RHI_FORMAT_B8G8R8A8_SINT = 49,
    RHI_FORMAT_B8G8R8A8_SRGB = 50,
    RHI_FORMAT_A2R10G10B10_UNORM_PACK32 = 58,
    RHI_FORMAT_A2R10G10B10_SNORM_PACK32 = 59,
    RHI_FORMAT_A2R10G10B10_UINT_PACK32 = 62,
    RHI_FORMAT_A2R10G10B10_SINT_PACK32 = 63,
    RHI_FORMAT_A2B10G10R10_UNORM_PACK32 = 64,
    RHI_FORMAT_A2B10G10R10_SNORM_PACK32 = 65,
    RHI_FORMAT_A2B10G10R10_UINT_PACK32 = 68,
    RHI_FORMAT_A2B10G10R10_SINT_PACK32 = 69,
    RHI_FORMAT_R16_UNORM = 70,
    RHI_FORMAT_R16_SNORM = 71,
    RHI_FORMAT_R16_UINT = 74,
    RHI_FORMAT_R16_SINT = 75,
    RHI_FORMAT_R16_SFLOAT = 76,
    RHI_FORMAT_R16G16_UNORM = 77,
    RHI_FORMAT_R16G16_SNORM = 78,
    RHI_FORMAT_R16G16_UINT = 81,
    RHI_FORMAT_R16G16_SINT = 82,
    RHI_FORMAT_R16G16_SFLOAT = 83,
    RHI_FORMAT_R16G16B16_UNORM = 84,
    RHI_FORMAT_R16G16B16_UINT = 88,
    RHI_FORMAT_R16G16B16_SINT = 89,
    RHI_FORMAT_R16G16B16_SFLOAT = 90,
    RHI_FORMAT_R16G16B16A16_UNORM = 91,
    RHI_FORMAT_R16G16B16A16_SNORM = 92,
    RHI_FORMAT_R16G16B16A16_UINT = 95,
    RHI_FORMAT_R16G16B16A16_SINT = 96,
    RHI_FORMAT_R16G16B16A16_SFLOAT = 97,
    RHI_FORMAT_R32_UINT = 98,
    RHI_FORMAT_R32_SINT = 99,
    RHI_FORMAT_R32_SFLOAT = 100,
    RHI_FORMAT_R32G32_UINT = 101,
    RHI_FORMAT_R32G32_SINT = 102,
    RHI_FORMAT_R32G32_SFLOAT = 103,
    RHI_FORMAT_R32G32B32_UINT = 104,
    RHI_FORMAT_R32G32B32_SINT = 105,
    RHI_FORMAT_R32G32B32_SFLOAT = 106,
    RHI_FORMAT_R32G32B32A32_UINT = 107,
    RHI_FORMAT_R32G32B32A32_SINT = 108,
    RHI_FORMAT_R32G32B32A32_SFLOAT = 109,
    RHI_FORMAT_B10G11R11_UFLOAT_PACK32 = 122,
    RHI_FORMAT_E5B9G9R9_UFLOAT_PACK32 = 123,
    RHI_FORMAT_D16_UNORM = 124,
    RHI_FORMAT_X8_D24_UNORM_PACK32 = 125,
    RHI_FORMAT_D32_SFLOAT = 126,
    RHI_FORMAT_S8_UINT = 127,
    RHI_FORMAT_D16_UNORM_S8_UINT = 128,
    RHI_FORMAT_D24_UNORM_S8_UINT = 129,
    RHI_FORMAT_D32_SFLOAT_S8_UINT = 130,
    RHI_FORMAT_BC1_RGB_UNORM_BLOCK = 131,
    RHI_FORMAT_BC1_RGB_SRGB_BLOCK = 132,
    RHI_FORMAT_BC1_RGBA_UNORM_BLOCK = 133,
    RHI_FORMAT_BC1_RGBA_SRGB_BLOCK = 134,
    RHI_FORMAT_BC2_UNORM_BLOCK = 135,
    RHI_FORMAT_BC2_SRGB_BLOCK = 136,
    RHI_FORMAT_BC3_UNORM_BLOCK = 137,
    RHI_FORMAT_BC3_SRGB_BLOCK = 138,
    RHI_FORMAT_BC4_UNORM_BLOCK = 139,
    RHI_FORMAT_BC4_SNORM_BLOCK = 140,
    RHI_FORMAT_BC5_UNORM_BLOCK = 141,
    RHI_FORMAT_BC5_SNORM_BLOCK = 142,
    RHI_FORMAT_BC6H_UFLOAT_BLOCK = 143,
    RHI_FORMAT_BC6H_SFLOAT_BLOCK = 144,
    RHI_FORMAT_BC7_UNORM_BLOCK = 145,
    RHI_FORMAT_BC7_SRGB_BLOCK = 146,
    RHI_FORMAT_MAX_ENUM = 0x7FFFFFFF
};

// ============================================================================
// RHIImageType
// ============================================================================
enum RHIImageType : int {
    RHI_IMAGE_TYPE_1D = 0,
    RHI_IMAGE_TYPE_2D = 1,
    RHI_IMAGE_TYPE_3D = 2,
    RHI_IMAGE_TYPE_MAX_ENUM = 0x7FFFFFFF
};

// ============================================================================
// RHIImageViewType
// ============================================================================
enum RHIImageViewType : int {
    RHI_IMAGE_VIEW_TYPE_1D = 0,
    RHI_IMAGE_VIEW_TYPE_2D = 1,
    RHI_IMAGE_VIEW_TYPE_3D = 2,
    RHI_IMAGE_VIEW_TYPE_CUBE = 3,
    RHI_IMAGE_VIEW_TYPE_1D_ARRAY = 4,
    RHI_IMAGE_VIEW_TYPE_2D_ARRAY = 5,
    RHI_IMAGE_VIEW_TYPE_CUBE_ARRAY = 6,
    RHI_IMAGE_VIEW_TYPE_MAX_ENUM = 0x7FFFFFFF
};

// ============================================================================
// RHIImageTiling
// ============================================================================
enum RHIImageTiling : int {
    RHI_IMAGE_TILING_OPTIMAL = 0,
    RHI_IMAGE_TILING_LINEAR = 1,
    RHI_IMAGE_TILING_MAX_ENUM = 0x7FFFFFFF
};

// ============================================================================
// RHIImageLayout — 图像布局
// ============================================================================
enum RHIImageLayout : int {
    RHI_IMAGE_LAYOUT_UNDEFINED = 0,
    RHI_IMAGE_LAYOUT_GENERAL = 1,
    RHI_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL = 2,
    RHI_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL = 3,
    RHI_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL = 4,
    RHI_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL = 5,
    RHI_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL = 6,
    RHI_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL = 7,
    RHI_IMAGE_LAYOUT_PREINITIALIZED = 8,
    RHI_IMAGE_LAYOUT_PRESENT_SRC_KHR = 1000001002,
    RHI_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL = 1000241000,
    RHI_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL = 1000241001,
    RHI_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL = 1000241002,
    RHI_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL = 1000241003,
    RHI_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL_KHR = 1000314001,
    RHI_IMAGE_LAYOUT_MAX_ENUM = 0x7FFFFFFF
};

// ============================================================================
// 位标志枚举 — typedef 为 uint32_t，使用时与 vk::Flags 直接 static_cast
// ============================================================================

enum RHIImageAspectFlagBits : std::uint32_t {
    RHI_IMAGE_ASPECT_COLOR_BIT = 0x00000001,
    RHI_IMAGE_ASPECT_DEPTH_BIT = 0x00000002,
    RHI_IMAGE_ASPECT_STENCIL_BIT = 0x00000004,
    RHI_IMAGE_ASPECT_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIImageAspectFlags = std::uint32_t;

enum RHIImageUsageFlagBits : std::uint32_t {
    RHI_IMAGE_USAGE_TRANSFER_SRC_BIT = 0x00000001,
    RHI_IMAGE_USAGE_TRANSFER_DST_BIT = 0x00000002,
    RHI_IMAGE_USAGE_SAMPLED_BIT = 0x00000004,
    RHI_IMAGE_USAGE_STORAGE_BIT = 0x00000008,
    RHI_IMAGE_USAGE_COLOR_ATTACHMENT_BIT = 0x00000010,
    RHI_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT = 0x00000020,
    RHI_IMAGE_USAGE_INPUT_ATTACHMENT_BIT = 0x00000080,
    RHI_IMAGE_USAGE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIImageUsageFlags = std::uint32_t;

enum RHIBufferUsageFlagBits : std::uint32_t {
    RHI_BUFFER_USAGE_TRANSFER_SRC_BIT = 0x00000001,
    RHI_BUFFER_USAGE_TRANSFER_DST_BIT = 0x00000002,
    RHI_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT = 0x00000004,
    RHI_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT = 0x00000008,
    RHI_BUFFER_USAGE_UNIFORM_BUFFER_BIT = 0x00000010,
    RHI_BUFFER_USAGE_STORAGE_BUFFER_BIT = 0x00000020,
    RHI_BUFFER_USAGE_INDEX_BUFFER_BIT = 0x00000040,
    RHI_BUFFER_USAGE_VERTEX_BUFFER_BIT = 0x00000080,
    RHI_BUFFER_USAGE_INDIRECT_BUFFER_BIT = 0x00000100,
    RHI_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT = 0x00020000,
    RHI_BUFFER_USAGE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIBufferUsageFlags = std::uint32_t;

enum RHIMemoryPropertyFlagBits : std::uint32_t {
    RHI_MEMORY_PROPERTY_DEVICE_LOCAL_BIT = 0x00000001,
    RHI_MEMORY_PROPERTY_HOST_VISIBLE_BIT = 0x00000002,
    RHI_MEMORY_PROPERTY_HOST_COHERENT_BIT = 0x00000004,
    RHI_MEMORY_PROPERTY_HOST_CACHED_BIT = 0x00000008,
    RHI_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT = 0x00000010,
    RHI_MEMORY_PROPERTY_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIMemoryPropertyFlags = std::uint32_t;

enum RHIShaderStageFlagBits : std::uint32_t {
    RHI_SHADER_STAGE_VERTEX_BIT = 0x00000001,
    RHI_SHADER_STAGE_TESSELLATION_CONTROL_BIT = 0x00000002,
    RHI_SHADER_STAGE_TESSELLATION_EVALUATION_BIT = 0x00000004,
    RHI_SHADER_STAGE_GEOMETRY_BIT = 0x00000008,
    RHI_SHADER_STAGE_FRAGMENT_BIT = 0x00000010,
    RHI_SHADER_STAGE_COMPUTE_BIT = 0x00000020,
    RHI_SHADER_STAGE_ALL_GRAPHICS = 0x0000001F,
    RHI_SHADER_STAGE_ALL = 0x7FFFFFFF,
    RHI_SHADER_STAGE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIShaderStageFlags = std::uint32_t;

enum RHIPipelineStageFlagBits : std::uint32_t {
    RHI_PIPELINE_STAGE_TOP_OF_PIPE_BIT = 0x00000001,
    RHI_PIPELINE_STAGE_DRAW_INDIRECT_BIT = 0x00000002,
    RHI_PIPELINE_STAGE_VERTEX_INPUT_BIT = 0x00000004,
    RHI_PIPELINE_STAGE_VERTEX_SHADER_BIT = 0x00000008,
    RHI_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT = 0x00000010,
    RHI_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT = 0x00000020,
    RHI_PIPELINE_STAGE_GEOMETRY_SHADER_BIT = 0x00000040,
    RHI_PIPELINE_STAGE_FRAGMENT_SHADER_BIT = 0x00000080,
    RHI_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT = 0x00000100,
    RHI_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT = 0x00000200,
    RHI_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT = 0x00000400,
    RHI_PIPELINE_STAGE_COMPUTE_SHADER_BIT = 0x00000800,
    RHI_PIPELINE_STAGE_TRANSFER_BIT = 0x00001000,
    RHI_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT = 0x00002000,
    RHI_PIPELINE_STAGE_HOST_BIT = 0x00004000,
    RHI_PIPELINE_STAGE_ALL_GRAPHICS = 0x00008000,
    RHI_PIPELINE_STAGE_ALL_COMMANDS = 0x00010000,
    RHI_PIPELINE_STAGE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIPipelineStageFlags = std::uint32_t;

enum RHIAccessFlagBits : std::uint32_t {
    RHI_ACCESS_INDIRECT_COMMAND_READ_BIT = 0x00000001,
    RHI_ACCESS_INDEX_READ_BIT = 0x00000002,
    RHI_ACCESS_VERTEX_ATTRIBUTE_READ_BIT = 0x00000004,
    RHI_ACCESS_UNIFORM_READ_BIT = 0x00000008,
    RHI_ACCESS_INPUT_ATTACHMENT_READ_BIT = 0x00000010,
    RHI_ACCESS_SHADER_READ_BIT = 0x00000020,
    RHI_ACCESS_SHADER_WRITE_BIT = 0x00000040,
    RHI_ACCESS_COLOR_ATTACHMENT_READ_BIT = 0x00000080,
    RHI_ACCESS_COLOR_ATTACHMENT_WRITE_BIT = 0x00000100,
    RHI_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT = 0x00000200,
    RHI_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT = 0x00000400,
    RHI_ACCESS_TRANSFER_READ_BIT = 0x00000800,
    RHI_ACCESS_TRANSFER_WRITE_BIT = 0x00001000,
    RHI_ACCESS_HOST_READ_BIT = 0x00002000,
    RHI_ACCESS_HOST_WRITE_BIT = 0x00004000,
    RHI_ACCESS_MEMORY_READ_BIT = 0x00008000,
    RHI_ACCESS_MEMORY_WRITE_BIT = 0x00010000,
    RHI_ACCESS_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIAccessFlags = std::uint32_t;

enum RHIDependencyFlagBits : std::uint32_t {
    RHI_DEPENDENCY_BY_REGION_BIT = 0x00000001,
    RHI_DEPENDENCY_DEVICE_GROUP_BIT = 0x00000004,
    RHI_DEPENDENCY_VIEW_LOCAL_BIT = 0x00000002,
    RHI_DEPENDENCY_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIDependencyFlags = std::uint32_t;

enum RHICullModeFlagBits : std::uint32_t {
    RHI_CULL_MODE_NONE = 0,
    RHI_CULL_MODE_FRONT_BIT = 0x00000001,
    RHI_CULL_MODE_BACK_BIT = 0x00000002,
    RHI_CULL_MODE_FRONT_AND_BACK = 0x00000003,
    RHI_CULL_MODE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHICullModeFlags = std::uint32_t;

enum RHIColorComponentFlagBits : std::uint32_t {
    RHI_COLOR_COMPONENT_R_BIT = 0x00000001,
    RHI_COLOR_COMPONENT_G_BIT = 0x00000002,
    RHI_COLOR_COMPONENT_B_BIT = 0x00000004,
    RHI_COLOR_COMPONENT_A_BIT = 0x00000008,
    RHI_COLOR_COMPONENT_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIColorComponentFlags = std::uint32_t;

enum RHISampleCountFlagBits : std::uint32_t {
    RHI_SAMPLE_COUNT_1_BIT = 0x00000001,
    RHI_SAMPLE_COUNT_2_BIT = 0x00000002,
    RHI_SAMPLE_COUNT_4_BIT = 0x00000004,
    RHI_SAMPLE_COUNT_8_BIT = 0x00000008,
    RHI_SAMPLE_COUNT_16_BIT = 0x00000010,
    RHI_SAMPLE_COUNT_32_BIT = 0x00000020,
    RHI_SAMPLE_COUNT_64_BIT = 0x00000040,
    RHI_SAMPLE_COUNT_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHISampleCountFlags = std::uint32_t;

enum RHICommandPoolCreateFlagBits : std::uint32_t {
    RHI_COMMAND_POOL_CREATE_TRANSIENT_BIT = 0x00000001,
    RHI_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT = 0x00000002,
    RHI_COMMAND_POOL_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHICommandPoolCreateFlags = std::uint32_t;

enum RHICommandBufferUsageFlagBits : std::uint32_t {
    RHI_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT = 0x00000001,
    RHI_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT = 0x00000002,
    RHI_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT = 0x00000004,
    RHI_COMMAND_BUFFER_USAGE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHICommandBufferUsageFlags = std::uint32_t;

enum RHIFenceCreateFlagBits : std::uint32_t {
    RHI_FENCE_CREATE_SIGNALED_BIT = 0x00000001,
    RHI_FENCE_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIFenceCreateFlags = std::uint32_t;

enum RHIImageCreateFlagBits : std::uint32_t {
    RHI_IMAGE_CREATE_SPARSE_BINDING_BIT = 0x00000001,
    RHI_IMAGE_CREATE_SPARSE_RESIDENCY_BIT = 0x00000002,
    RHI_IMAGE_CREATE_SPARSE_ALIASED_BIT = 0x00000004,
    RHI_IMAGE_CREATE_MUTABLE_FORMAT_BIT = 0x00000008,
    RHI_IMAGE_CREATE_CUBE_COMPATIBLE_BIT = 0x00000010,
    RHI_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT = 0x00000020,
    RHI_IMAGE_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIImageCreateFlags = std::uint32_t;

enum RHIBufferCreateFlagBits : std::uint32_t {
    RHI_BUFFER_CREATE_SPARSE_BINDING_BIT = 0x00000001,
    RHI_BUFFER_CREATE_SPARSE_RESIDENCY_BIT = 0x00000002,
    RHI_BUFFER_CREATE_SPARSE_ALIASED_BIT = 0x00000004,
    RHI_BUFFER_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIBufferCreateFlags = std::uint32_t;

enum RHIDescriptorPoolCreateFlagBits : std::uint32_t {
    RHI_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT = 0x00000001,
    RHI_DESCRIPTOR_POOL_CREATE_UPDATE_AFTER_BIND_BIT = 0x00000002,
    RHI_DESCRIPTOR_POOL_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIDescriptorPoolCreateFlags = std::uint32_t;

enum RHIDescriptorSetLayoutCreateFlagBits : std::uint32_t {
    RHI_DESCRIPTOR_SET_LAYOUT_CREATE_UPDATE_AFTER_BIND_POOL_BIT = 0x00000002,
    RHI_DESCRIPTOR_SET_LAYOUT_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIDescriptorSetLayoutCreateFlags = std::uint32_t;

enum RHIAttachmentDescriptionFlagBits : std::uint32_t {
    RHI_ATTACHMENT_DESCRIPTION_MAY_ALIAS_BIT = 0x00000001,
    RHI_ATTACHMENT_DESCRIPTION_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIAttachmentDescriptionFlags = std::uint32_t;

enum RHISubpassDescriptionFlagBits : std::uint32_t {
    RHI_SUBPASS_DESCRIPTION_PER_VIEW_ATTRIBUTES_BIT = 0x00000001,
    RHI_SUBPASS_DESCRIPTION_PER_VIEW_POSITION_X_ONLY_BIT = 0x00000002,
    RHI_SUBPASS_DESCRIPTION_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHISubpassDescriptionFlags = std::uint32_t;

enum RHIPipelineCreateFlagBits : std::uint32_t {
    RHI_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT = 0x00000001,
    RHI_PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT = 0x00000002,
    RHI_PIPELINE_CREATE_DERIVATIVE_BIT = 0x00000004,
    RHI_PIPELINE_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIPipelineCreateFlags = std::uint32_t;

enum RHIPipelineShaderStageCreateFlagBits : std::uint32_t {
    RHI_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT = 0x00000001,
    RHI_PIPELINE_SHADER_STAGE_CREATE_REQUIRE_FULL_SUBGROUPS_BIT = 0x00000002,
    RHI_PIPELINE_SHADER_STAGE_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIPipelineShaderStageCreateFlags = std::uint32_t;

enum RHISemaphoreCreateFlagBits : std::uint32_t {
    RHI_SEMAPHORE_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHISemaphoreCreateFlags = std::uint32_t;

enum RHICommandPoolResetFlagBits : std::uint32_t {
    RHI_COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT = 0x00000001,
    RHI_COMMAND_POOL_RESET_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHICommandPoolResetFlags = std::uint32_t;

enum RHIMemoryMapFlagBits : std::uint32_t {
    RHI_MEMORY_MAP_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIMemoryMapFlags = std::uint32_t;

enum RHIFramebufferCreateFlagBits : std::uint32_t {
    RHI_FRAMEBUFFER_CREATE_IMAGELESS_BIT = 0x00000001,
    RHI_FRAMEBUFFER_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIFramebufferCreateFlags = std::uint32_t;

enum RHIRenderPassCreateFlagBits : std::uint32_t {
    RHI_RENDER_PASS_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIRenderPassCreateFlags = std::uint32_t;

enum RHIPipelineLayoutCreateFlagBits : std::uint32_t {
    RHI_PIPELINE_LAYOUT_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIPipelineLayoutCreateFlags = std::uint32_t;

enum RHISamplerCreateFlagBits : std::uint32_t {
    RHI_SAMPLER_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHISamplerCreateFlags = std::uint32_t;

enum RHIShaderModuleCreateFlagBits : std::uint32_t {
    RHI_SHADER_MODULE_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIShaderModuleCreateFlags = std::uint32_t;

enum RHIImageViewCreateFlagBits : std::uint32_t {
    RHI_IMAGE_VIEW_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIImageViewCreateFlags = std::uint32_t;

enum RHIDeviceCreateFlagBits : std::uint32_t {
    RHI_DEVICE_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIDeviceCreateFlags = std::uint32_t;

enum RHIInstanceCreateFlagBits : std::uint32_t {
    RHI_INSTANCE_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIInstanceCreateFlags = std::uint32_t;

enum RHIDeviceQueueCreateFlagBits : std::uint32_t {
    RHI_DEVICE_QUEUE_CREATE_PROTECTED_BIT = 0x00000001,
    RHI_DEVICE_QUEUE_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIDeviceQueueCreateFlags = std::uint32_t;

enum RHIMemoryHeapFlagBits : std::uint32_t {
    RHI_MEMORY_HEAP_DEVICE_LOCAL_BIT = 0x00000001,
    RHI_MEMORY_HEAP_MULTI_INSTANCE_BIT = 0x00000002,
    RHI_MEMORY_HEAP_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIMemoryHeapFlags = std::uint32_t;

enum RHIQueueFlagBits : std::uint32_t {
    RHI_QUEUE_GRAPHICS_BIT = 0x00000001,
    RHI_QUEUE_COMPUTE_BIT = 0x00000002,
    RHI_QUEUE_TRANSFER_BIT = 0x00000004,
    RHI_QUEUE_SPARSE_BINDING_BIT = 0x00000008,
    RHI_QUEUE_PROTECTED_BIT = 0x00000010,
    RHI_QUEUE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIQueueFlags = std::uint32_t;

enum RHIPipelineColorBlendStateCreateFlagBits : std::uint32_t {
    RHI_PIPELINE_COLOR_BLEND_STATE_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIPipelineColorBlendStateCreateFlags = std::uint32_t;

enum RHIPipelineDepthStencilStateCreateFlagBits : std::uint32_t {
    RHI_PIPELINE_DEPTH_STENCIL_STATE_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIPipelineDepthStencilStateCreateFlags = std::uint32_t;

enum RHIPipelineDynamicStateCreateFlagBits : std::uint32_t {
    RHI_PIPELINE_DYNAMIC_STATE_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIPipelineDynamicStateCreateFlags = std::uint32_t;

enum RHIPipelineInputAssemblyStateCreateFlagBits : std::uint32_t {
    RHI_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIPipelineInputAssemblyStateCreateFlags = std::uint32_t;

enum RHIPipelineMultisampleStateCreateFlagBits : std::uint32_t {
    RHI_PIPELINE_MULTISAMPLE_STATE_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIPipelineMultisampleStateCreateFlags = std::uint32_t;

enum RHIPipelineRasterizationStateCreateFlagBits : std::uint32_t {
    RHI_PIPELINE_RASTERIZATION_STATE_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIPipelineRasterizationStateCreateFlags = std::uint32_t;

enum RHIPipelineTessellationStateCreateFlagBits : std::uint32_t {
    RHI_PIPELINE_TESSELLATION_STATE_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIPipelineTessellationStateCreateFlags = std::uint32_t;

enum RHIPipelineVertexInputStateCreateFlagBits : std::uint32_t {
    RHI_PIPELINE_VERTEX_INPUT_STATE_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIPipelineVertexInputStateCreateFlags = std::uint32_t;

enum RHIPipelineViewportStateCreateFlagBits : std::uint32_t {
    RHI_PIPELINE_VIEWPORT_STATE_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
};
using RHIPipelineViewportStateCreateFlags = std::uint32_t;

// ============================================================================
// 非位标志枚举
// ============================================================================

enum RHIDescriptorType : int {
    RHI_DESCRIPTOR_TYPE_SAMPLER = 0,
    RHI_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER = 1,
    RHI_DESCRIPTOR_TYPE_SAMPLED_IMAGE = 2,
    RHI_DESCRIPTOR_TYPE_STORAGE_IMAGE = 3,
    RHI_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER = 4,
    RHI_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER = 5,
    RHI_DESCRIPTOR_TYPE_UNIFORM_BUFFER = 6,
    RHI_DESCRIPTOR_TYPE_STORAGE_BUFFER = 7,
    RHI_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC = 8,
    RHI_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC = 9,
    RHI_DESCRIPTOR_TYPE_INPUT_ATTACHMENT = 10,
    RHI_DESCRIPTOR_TYPE_MAX_ENUM = 0x7FFFFFFF
};

enum RHICompareOp : int {
    RHI_COMPARE_OP_NEVER = 0,
    RHI_COMPARE_OP_LESS = 1,
    RHI_COMPARE_OP_EQUAL = 2,
    RHI_COMPARE_OP_LESS_OR_EQUAL = 3,
    RHI_COMPARE_OP_GREATER = 4,
    RHI_COMPARE_OP_NOT_EQUAL = 5,
    RHI_COMPARE_OP_GREATER_OR_EQUAL = 6,
    RHI_COMPARE_OP_ALWAYS = 7,
    RHI_COMPARE_OP_MAX_ENUM = 0x7FFFFFFF
};

enum RHIFilter : int {
    RHI_FILTER_NEAREST = 0,
    RHI_FILTER_LINEAR = 1,
    RHI_FILTER_MAX_ENUM = 0x7FFFFFFF
};

enum RHISamplerMipmapMode : int {
    RHI_SAMPLER_MIPMAP_MODE_NEAREST = 0,
    RHI_SAMPLER_MIPMAP_MODE_LINEAR = 1,
    RHI_SAMPLER_MIPMAP_MODE_MAX_ENUM = 0x7FFFFFFF
};

enum RHISamplerAddressMode : int {
    RHI_SAMPLER_ADDRESS_MODE_REPEAT = 0,
    RHI_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT = 1,
    RHI_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE = 2,
    RHI_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER = 3,
    RHI_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE = 4,
    RHI_SAMPLER_ADDRESS_MODE_MAX_ENUM = 0x7FFFFFFF
};

enum RHIPrimitiveTopology : int {
    RHI_PRIMITIVE_TOPOLOGY_POINT_LIST = 0,
    RHI_PRIMITIVE_TOPOLOGY_LINE_LIST = 1,
    RHI_PRIMITIVE_TOPOLOGY_LINE_STRIP = 2,
    RHI_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST = 3,
    RHI_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP = 4,
    RHI_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN = 5,
    RHI_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY = 6,
    RHI_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY = 7,
    RHI_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY = 8,
    RHI_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY = 9,
    RHI_PRIMITIVE_TOPOLOGY_PATCH_LIST = 10,
    RHI_PRIMITIVE_TOPOLOGY_MAX_ENUM = 0x7FFFFFFF
};

enum RHIPolygonMode : int {
    RHI_POLYGON_MODE_FILL = 0,
    RHI_POLYGON_MODE_LINE = 1,
    RHI_POLYGON_MODE_POINT = 2,
    RHI_POLYGON_MODE_MAX_ENUM = 0x7FFFFFFF
};

enum RHIFrontFace : int {
    RHI_FRONT_FACE_COUNTER_CLOCKWISE = 0,
    RHI_FRONT_FACE_CLOCKWISE = 1,
    RHI_FRONT_FACE_MAX_ENUM = 0x7FFFFFFF
};

enum RHILogicOp : int {
    RHI_LOGIC_OP_CLEAR = 0,
    RHI_LOGIC_OP_AND = 1,
    RHI_LOGIC_OP_AND_REVERSE = 2,
    RHI_LOGIC_OP_COPY = 3,
    RHI_LOGIC_OP_AND_INVERTED = 4,
    RHI_LOGIC_OP_NO_OP = 5,
    RHI_LOGIC_OP_XOR = 6,
    RHI_LOGIC_OP_OR = 7,
    RHI_LOGIC_OP_NOR = 8,
    RHI_LOGIC_OP_EQUIVALENT = 9,
    RHI_LOGIC_OP_INVERT = 10,
    RHI_LOGIC_OP_OR_REVERSE = 11,
    RHI_LOGIC_OP_COPY_INVERTED = 12,
    RHI_LOGIC_OP_OR_INVERTED = 13,
    RHI_LOGIC_OP_NAND = 14,
    RHI_LOGIC_OP_SET = 15,
    RHI_LOGIC_OP_MAX_ENUM = 0x7FFFFFFF
};

enum RHIBlendFactor : int {
    RHI_BLEND_FACTOR_ZERO = 0,
    RHI_BLEND_FACTOR_ONE = 1,
    RHI_BLEND_FACTOR_SRC_COLOR = 2,
    RHI_BLEND_FACTOR_ONE_MINUS_SRC_COLOR = 3,
    RHI_BLEND_FACTOR_DST_COLOR = 4,
    RHI_BLEND_FACTOR_ONE_MINUS_DST_COLOR = 5,
    RHI_BLEND_FACTOR_SRC_ALPHA = 6,
    RHI_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA = 7,
    RHI_BLEND_FACTOR_DST_ALPHA = 8,
    RHI_BLEND_FACTOR_ONE_MINUS_DST_ALPHA = 9,
    RHI_BLEND_FACTOR_CONSTANT_COLOR = 10,
    RHI_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR = 11,
    RHI_BLEND_FACTOR_CONSTANT_ALPHA = 12,
    RHI_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA = 13,
    RHI_BLEND_FACTOR_SRC_ALPHA_SATURATE = 14,
    RHI_BLEND_FACTOR_SRC1_COLOR = 15,
    RHI_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR = 16,
    RHI_BLEND_FACTOR_SRC1_ALPHA = 17,
    RHI_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA = 18,
    RHI_BLEND_FACTOR_MAX_ENUM = 0x7FFFFFFF
};

enum RHIBlendOp : int {
    RHI_BLEND_OP_ADD = 0,
    RHI_BLEND_OP_SUBTRACT = 1,
    RHI_BLEND_OP_REVERSE_SUBTRACT = 2,
    RHI_BLEND_OP_MIN = 3,
    RHI_BLEND_OP_MAX = 4,
    RHI_BLEND_OP_MAX_ENUM = 0x7FFFFFFF
};

enum RHIStencilOp : int {
    RHI_STENCIL_OP_KEEP = 0,
    RHI_STENCIL_OP_ZERO = 1,
    RHI_STENCIL_OP_REPLACE = 2,
    RHI_STENCIL_OP_INCREMENT_AND_CLAMP = 3,
    RHI_STENCIL_OP_DECREMENT_AND_CLAMP = 4,
    RHI_STENCIL_OP_INVERT = 5,
    RHI_STENCIL_OP_INCREMENT_AND_WRAP = 6,
    RHI_STENCIL_OP_DECREMENT_AND_WRAP = 7,
    RHI_STENCIL_OP_MAX_ENUM = 0x7FFFFFFF
};

enum RHIVertexInputRate : int {
    RHI_VERTEX_INPUT_RATE_VERTEX = 0,
    RHI_VERTEX_INPUT_RATE_INSTANCE = 1,
    RHI_VERTEX_INPUT_RATE_MAX_ENUM = 0x7FFFFFFF
};

enum RHIBorderColor : int {
    RHI_BORDER_COLOR_FLOAT_TRANSPARENT_BLACK = 0,
    RHI_BORDER_COLOR_INT_TRANSPARENT_BLACK = 1,
    RHI_BORDER_COLOR_FLOAT_OPAQUE_BLACK = 2,
    RHI_BORDER_COLOR_INT_OPAQUE_BLACK = 3,
    RHI_BORDER_COLOR_FLOAT_OPAQUE_WHITE = 4,
    RHI_BORDER_COLOR_INT_OPAQUE_WHITE = 5,
    RHI_BORDER_COLOR_MAX_ENUM = 0x7FFFFFFF
};

enum RHIDynamicState : int {
    RHI_DYNAMIC_STATE_VIEWPORT = 0,
    RHI_DYNAMIC_STATE_SCISSOR = 1,
    RHI_DYNAMIC_STATE_LINE_WIDTH = 2,
    RHI_DYNAMIC_STATE_DEPTH_BIAS = 3,
    RHI_DYNAMIC_STATE_BLEND_CONSTANTS = 4,
    RHI_DYNAMIC_STATE_DEPTH_BOUNDS = 5,
    RHI_DYNAMIC_STATE_STENCIL_COMPARE_MASK = 6,
    RHI_DYNAMIC_STATE_STENCIL_WRITE_MASK = 7,
    RHI_DYNAMIC_STATE_STENCIL_REFERENCE = 8,
    RHI_DYNAMIC_STATE_CULL_MODE_EXT = 1000267000,
    RHI_DYNAMIC_STATE_FRONT_FACE_EXT = 1000267001,
    RHI_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY_EXT = 1000267002,
    RHI_DYNAMIC_STATE_VIEWPORT_WITH_COUNT_EXT = 1000267003,
    RHI_DYNAMIC_STATE_SCISSOR_WITH_COUNT_EXT = 1000267004,
    RHI_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE_EXT = 1000267005,
    RHI_DYNAMIC_STATE_DEPTH_TEST_ENABLE_EXT = 1000267006,
    RHI_DYNAMIC_STATE_DEPTH_WRITE_ENABLE_EXT = 1000267007,
    RHI_DYNAMIC_STATE_DEPTH_COMPARE_OP_EXT = 1000267008,
    RHI_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE_EXT = 1000267009,
    RHI_DYNAMIC_STATE_STENCIL_TEST_ENABLE_EXT = 1000267010,
    RHI_DYNAMIC_STATE_STENCIL_OP_EXT = 1000267011,
    RHI_DYNAMIC_STATE_MAX_ENUM = 0x7FFFFFFF
};

enum RHIPhysicalDeviceType : int {
    RHI_PHYSICAL_DEVICE_TYPE_OTHER = 0,
    RHI_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU = 1,
    RHI_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU = 2,
    RHI_PHYSICAL_DEVICE_TYPE_VIRTUAL_GPU = 3,
    RHI_PHYSICAL_DEVICE_TYPE_CPU = 4,
    RHI_PHYSICAL_DEVICE_TYPE_MAX_ENUM = 0x7FFFFFFF
};

enum RHIPipelineBindPoint : int {
    RHI_PIPELINE_BIND_POINT_GRAPHICS = 0,
    RHI_PIPELINE_BIND_POINT_COMPUTE = 1,
    RHI_PIPELINE_BIND_POINT_MAX_ENUM = 0x7FFFFFFF
};

enum RHICommandBufferLevel : int {
    RHI_COMMAND_BUFFER_LEVEL_PRIMARY = 0,
    RHI_COMMAND_BUFFER_LEVEL_SECONDARY = 1,
    RHI_COMMAND_BUFFER_LEVEL_MAX_ENUM = 0x7FFFFFFF
};

enum RHISharingMode : int {
    RHI_SHARING_MODE_EXCLUSIVE = 0,
    RHI_SHARING_MODE_CONCURRENT = 1,
    RHI_SHARING_MODE_MAX_ENUM = 0x7FFFFFFF
};

enum RHIAttachmentLoadOp : int {
    RHI_ATTACHMENT_LOAD_OP_LOAD = 0,
    RHI_ATTACHMENT_LOAD_OP_CLEAR = 1,
    RHI_ATTACHMENT_LOAD_OP_DONT_CARE = 2,
    RHI_ATTACHMENT_LOAD_OP_MAX_ENUM = 0x7FFFFFFF
};

enum RHIAttachmentStoreOp : int {
    RHI_ATTACHMENT_STORE_OP_STORE = 0,
    RHI_ATTACHMENT_STORE_OP_DONT_CARE = 1,
    RHI_ATTACHMENT_STORE_OP_NONE_KHR = 1000301000,
    RHI_ATTACHMENT_STORE_OP_MAX_ENUM = 0x7FFFFFFF
};

enum RHIComponentSwizzle : int {
    RHI_COMPONENT_SWIZZLE_IDENTITY = 0,
    RHI_COMPONENT_SWIZZLE_ZERO = 1,
    RHI_COMPONENT_SWIZZLE_ONE = 2,
    RHI_COMPONENT_SWIZZLE_R = 3,
    RHI_COMPONENT_SWIZZLE_G = 4,
    RHI_COMPONENT_SWIZZLE_B = 5,
    RHI_COMPONENT_SWIZZLE_A = 6,
    RHI_COMPONENT_SWIZZLE_MAX_ENUM = 0x7FFFFFFF
};

enum RHISubpassContents : int {
    RHI_SUBPASS_CONTENTS_INLINE = 0,
    RHI_SUBPASS_CONTENTS_SECONDARY_COMMAND_BUFFERS = 1,
    RHI_SUBPASS_CONTENTS_MAX_ENUM = 0x7FFFFFFF
};

enum RHIIndexType : int {
    RHI_INDEX_TYPE_UINT16 = 0,
    RHI_INDEX_TYPE_UINT32 = 1,
    RHI_INDEX_TYPE_MAX_ENUM = 0x7FFFFFFF
};

// ============================================================================
// RHI 自定义枚举（非 Vulkan 映射）
// ============================================================================
enum RHIDefaultSamplerType : int {
    RHI_DEFAULT_SAMPLER_LINEAR = 0,
    RHI_DEFAULT_SAMPLER_NEAREST = 1
};

} // namespace Crumb::Render
